http://127.0.0.1:8000/test

###

POST http://127.0.0.1:8000/test
Content-Type: application/json

{
    "question": "あなたは誰ですか？簡単にどういうツールなのか、自己紹介してください。また、あなたが得意なことと苦手なことを、日本語で教えてください。また、ChatGPTなどのLLMとの棲み分けを教えてください。英語と日本語、どちらが得意ですか？"
}