http://127.0.0.1:8000/test

###

POST http://127.0.0.1:8000/test
Content-Type: application/json

{
    "question": "あなたはこの作品を面白いと思いましたか？日本語で詳しく、300文字程度で、あなたの感想を教えてください。最後に記述した文字数と、また、同じ作者の別の作品で、おすすめがあれば教えてください。"
}